### ISSUE TITLE
Please remove git-commit-mode and git-rebase-mode

### ISSUE THREAD

**Issue by tarsius** [nicferrier/elmarmalade#111]
They have been renamed to just `git-commit` and `git-rebase`. Thanks.

**Comment by nicferrier** [comment]
Done.

You did not exist as a user before... I've added you now and sent you an email in the usual way. I've also moved git-commit to you.

**Comment by tarsius** [comment]
Thanks for looking into this. Unfortunately it doesn't work yet.

> You did not exist as a user before...

I did login a few times during the last few days and I was able to upload several packages.

> I've added you now and sent you an email in the usual way.

I tried logging in before I saw the mail. It no longer worked. After I clicked on the link in the mail and inserted the password twice, I was able to login again.

> [git-config-mode]

I was able to upload the latest release.

> I've also moved git-commit to you.

I can confirm that this package is now listed on https://marmalade-repo.org/profile/tarsius/. However I was unable to upload a new version. I do get a token, but when I try to use that to upload the new release I get `curl: (52) Empty reply from server`.

Additionally several other packages that were listed on that page just a day ago, no longer are.

That includes git-commit-mode and git-rebase-mode, which is expected, since you removed them. But then I checked whether the pages https://marmalade-repo.org/packages/git-commit-mode and https://marmalade-repo.org/packages/git-rebase-mode still exist, and they do. Might be a caching issue. Then I checked whether they are still listed in archive-contents (as downloaded by package.el) and they are.

The other packages that are no longer listed on https://marmalade-repo.org/profile/tarsius/ are: with-editor, magit-popup, and gitattributes-mode. The first two packages I have first uploaded on 2th July. They did not exist on marmalade before then. gitattributes-mode already existed before then, but on the 2th I successfully uploaded 1.2.0.

I am unable to test whether I am nevertheless able to upload new releases for these packages, because the releases I uploaded on the 2th are the latest releases. So I have nothing new to test with.

---

Here is a list of what is required and what actually works:
- [x] web login as tarsius
- [x] aquire token for tarsius
- [ ] gitattributes-mode
  - [ ] owned by me
  - [ ] can push
- [x] gitconfig-mode
  - [x] owned by me
  - [x] can push (as of 4.7)
- [x] gitignore-mode
  - [x] owned by me
  - [x] can push (as of 2.7)
- [x] with-editor
  - [ ] owned by me
  - [ ] can push
- [ ] git-commit
  - [x] owned by me
  - [ ] can push (failed on 4.7)
- [ ] magit-popup
  - [ ] owned by me
  - [ ] can push
- [ ] magit
  - [ ] owned by me
  - [ ] can push (as of 2.7)
- [ ] remove git-commit-mode
  - [x] remove from profile/tarsius
  - [ ] remove from packages/git-commit-mode
  - [ ] remove from archive-contents
- [ ] remove git-rebase-mode
  - [x] remove from profile/tarsius
  - [ ] remove from packages/git-rebase-mode
  - [ ] remove from archive-contents

Whether a package is owned by my I verify by checking whether it is listed on https://marmalade-repo.org/profile/tarsius/.

**Comment by nicferrier** [comment]
Made with-editor owned by you
made gitattributes-mode owned by you
made git-commit owned by you
made magit-popup owned by you
made magit owned by you

I'm not sure I removed git-rebase-mode or git-commit-mode

What's the justification for removing those again?

Have the authors of those modes moved on to be  adopted by magit?

**Comment by tarsius** [comment]
> Made ... owned by you

I can confirm that this worked.

**Except that I still get `curl: (52) Empty reply from server` when trying to upload `git-commit-2.1.0.el`.**

> I'm not sure I removed git-rebase-mode or git-commit-mode

They still appear in `archive-contents`.

> What's the justification for removing those again?

They were renamed by removing the `-mode` suffix. So the packages with the suffix are just older versions of those without the suffix.

> Have the authors of those modes moved on to be adopted by magit?

`git-rebase{-mode}` was always part of Magit. And `git-commit{-mode}` became part of the Magit project about two years ago. I am the maintainer of these packages and have dropped the suffix.

**Comment by nicferrier** [comment]
I've assigned you to own git-commit-mode and git-rebase-mode

You're getting the error from curl because your package is badly defined. There's no version as far as I can see.

Sorry, the error response from marmalade is terrible.

You can check this stuff yourself (and the marmalade client really should do this as well) by doing:

```
M-: (package-buffer-info)
```

on the package buffer (there's a tar equivalent as well).

**Comment by tarsius** [comment]
> You're getting the error from curl because your package is badly defined. There's no version as far as I can see.

Indeed. I missed that. I added Package-Version and now it works. Thanks, and sorry.

> I've assigned you to own git-commit-mode and git-rebase-mode

That worked. I was able to remove them.

---

Everything appears to be working now. Thanks a lot!
